#:schema node_modules/wrangler/config-schema.json
name = "cotask"
main = "src/index.ts"
compatibility_date = "2024-10-11"
compatibility_flags = ["nodejs_compat"]


[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "dbtest2"
database_id = "fbde9324-899a-4bfc-acd1-faf70b7e8cb4"
migrations_dir = "src/database/drizzle"